language: ruby
env:
  global:
    secure: "JOt170FbJYWUAIg6vDlMOd/g1Iwf7KG0jyOhCSjdOUSyBdMuu4M7PWULDKg/axtQ8hGW2+fGfBz+8bjg2N1pAiO+M23haGBuA1TaF8gWAViLFbwmk9qjnw23lrogmwkaP0Y42mZtxHGe1AuB2hctWKym3H/Wgsrku+/pWAi6Mvc="
before_script:
- gem install jekyll --version '= 1.5.1'
- gem install RedCloth
script:
- jekyll build
after_script:
- ls
- chmod a+x travis-promote.sh
- ./travis-promote.sh
