name: UML Designer Documentation
markdown: redcarpet
pygments: false
exclude: ['vagrant.sh', 'Vagrantfile', '.vagrant']
paginate: 5
paginate_path: "blog/page:num"
#baseurl: http://uml-designer.github.io/documentation
